### ISSUE TITLE
Create clickable graphic

### ISSUE THREAD

**Issue by fredericle** [michelin/Continuous-Architecture-Toolkit#5]
Two techniques can be used, image maps or links. Links would be easier to maintain as the site will grow in complexity:

- The file ca-big-picture.svg in the framework directory shows how links could be used.
- The file PAGE-DE-GARDE-PSD.html in the same directory shows how image maps could be used.

You can open the files in a browser and test how it works by clicking on the "Enterprise" and "Strategic DDD" icons for the ca-big-picture svg image and by clicking on graphical elements in PAGE-DE-GARDE-PSD.

**Comment by ojauze** [comment]
done using 
`++++
<object type="image/svg+xml" data="img/ca-framework-v08.svg">Your browser does not support SVGs</object>
++++`
